// Generated using Sourcery 0.17.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

extension Token {

  public var isKeyword: Bool {
    switch kind {
    case .associatedtype:
      return true
    case .class:
      return true
    case .`deinit`:
      return true
    case .enum:
      return true
    case .extension:
      return true
    case .fileprivate:
      return true
    case .func:
      return true
    case .import:
      return true
    case .`init`:
      return true
    case .inout:
      return true
    case .internal:
      return true
    case .let:
      return true
    case .open:
      return true
    case .operator:
      return true
    case .private:
      return true
    case .protocol:
      return true
    case .public:
      return true
    case .rethrows:
      return true
    case .static:
      return true
    case .struct:
      return true
    case .subscript:
      return true
    case .typealias:
      return true
    case .var:
      return true
    case .break:
      return true
    case .case:
      return true
    case .continue:
      return true
    case .default:
      return true
    case .defer:
      return true
    case .do:
      return true
    case .else:
      return true
    case .fallthrough:
      return true
    case .for:
      return true
    case .guard:
      return true
    case .if:
      return true
    case .in:
      return true
    case .repeat:
      return true
    case .return:
      return true
    case .switch:
      return true
    case .where:
      return true
    case .while:
      return true
    case .as:
      return true
    case .Any:
      return true
    case .catch:
      return true
    case .false:
      return true
    case .is:
      return true
    case .nil:
      return true
    case .super:
      return true
    case .`self`:
      return true
    case .`Self`:
      return true
    case .throw:
      return true
    case .throws:
      return true
    case .true:
      return true
    case .try:
      return true
    case .associativity:
      return true
    case .convenience:
      return true
    case .dynamic:
      return true
    case .didSet:
      return true
    case .final:
      return true
    case .get:
      return true
    case .infix:
      return true
    case .indirect:
      return true
    case .lazy:
      return true
    case .left:
      return true
    case .mutating:
      return true
    case .none:
      return true
    case .nonmutating:
      return true
    case .optional:
      return true
    case .override:
      return true
    case .postfix:
      return true
    case .precedence:
      return true
    case .prefix:
      return true
    case .Protocol:
      return true
    case .required:
      return true
    case .right:
      return true
    case .set:
      return true
    case .Type:
      return true
    case .unowned:
      return true
    case .weak:
      return true
    case .willset:
      return true
    case .owned:
      return true
    case .shared:
      return true
    case ._available:
      return true
    case ._colorLiteral:
      return true
    case ._column:
      return true
    case ._else:
      return true
    case ._elseif:
      return true
    case ._endif:
      return true
    case ._error:
      return true
    case ._file:
      return true
    case ._fileLiteral:
      return true
    case ._function:
      return true
    case ._if:
      return true
    case ._imageLiteral:
      return true
    case ._line:
      return true
    case ._selector:
      return true
    case ._sourceLocation:
      return true
    case ._warning:
      return true
    default:
      return false
    }
  }

}
